### ISSUE TITLE
What is the database schema?

### ISSUE THREAD

**Issue by deGravity** [dtl-nyuad/qetch#1]
Can you provide a script for creating the proper tables in the postgres database? I tried to reverse engineer the schema by reading through the import script. This got the import script to run mostly without errors, but when I run the server I don't see any data sets.

Awesome work and thanks!

**Comment by miromannino** [comment]
Hello, the script is in `Datasets/psdb.txt` with also some simple instructions on how to install postgres.

You are welcome! And thank you for asking, it could be useful for others too!
